import Navbar from '@/components/navbar/navbar';
import './globals.css';
import type { Metadata } from 'next';
import { Work_Sans } from 'next/font/google';
import { ThemeContextProvider } from '@/context/ThemeContext';
import ThemeProvider from '@/components/providers/ThemeProvider';

const inter = Work_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeContextProvider>
          <ThemeProvider>
            <div className="container">
              <Navbar />
              <div className="wrapper">{children}</div>
            </div>
          </ThemeProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
